#define _DEFAULT_SOURCE
#define _BSD_SOURCE
#define _GNU_SOURCE

#include <inttypes.h>
#include <locale.h>
#include <math.h>
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <uchar.h>
#include <wchar.h>
#include <wctype.h>

#include <arpa/inet.h>
#include <dirent.h>
#include <fcntl.h>
#include <grp.h>
#include <netdb.h>
#include <pthread.h>
#include <poll.h>
#include <pwd.h>
#include <signal.h>
#include <termios.h>
#include <unistd.h>
#include <sys/file.h>
#include <sys/ipc.h>
#include <sys/mman.h>
#include <sys/msg.h>
#include <sys/resource.h>
#include <sys/sem.h>
#include <sys/socket.h>
#include <sys/shm.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/types.h>
#include <sys/wait.h>

#include <aliases.h>
#include <argp.h>
#include <argz.h>
#include <envz.h>
#include <err.h>
#include <error.h>
#include <execinfo.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <fstab.h>
#include <fts.h>
#include <ftw.h>
#include <glob.h>
#include <gnu/libc-version.h>
#include <gshadow.h>
#include <iconv.h>
#include <ifaddrs.h>
#include <langinfo.h>
#include <libaudit.h>
#include <libgen.h>
#include <libintl.h>
#include <link.h>
#include <malloc.h>
#include <mcheck.h>
#include <monetary.h>
#include <mntent.h>
#include <net/if.h>
#include <netinet/ether.h>
#include <obstack.h>
#include <printf.h>
#define _REGEX_RE_COMP
#include <regex.h>
#include <search.h>
#include <sgtty.h>
#include <syslog.h>
#include <sched.h>
#include <shadow.h>
#include <spawn.h>
#include <stropts.h>
#include <ttyent.h>
#include <ucontext.h>
#include <ulimit.h>
#include <ustat.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <wordexp.h>
#include <sys/auxv.h>
#include <sys/capability.h>
#include <sys/epoll.h>
#include <sys/eventfd.h>
#include <sys/fanotify.h>
#include <sys/fsuid.h>
#include <sys/gmon.h>
#include <sys/inotify.h>
#include <sys/io.h>
#include <sys/kdaemon.h>
#include <sys/klog.h>
#include <sys/mount.h>
#include <sys/personality.h>
#include <sys/prctl.h>
#include <sys/profil.h>
#include <sys/ptrace.h>
#include <sys/quota.h>
#include <sys/reboot.h>
#include <sys/sendfile.h>
#include <sys/signalfd.h>
#include <sys/statvfs.h>
#include <sys/swap.h>
#include <sys/sysctl.h>
#include <sys/sysinfo.h>
#include <sys/timeb.h>
#include <sys/timerfd.h>
#include <sys/timex.h>
#include <sys/utsname.h>
#include <sys/vfs.h>
#include <sys/vlimit.h>
#include <sys/vtimes.h>
#include <sys/xattr.h>
#include <rpc/des_crypt.h>
#include <rpc/key_prot.h>
#include <rpc/pmap_clnt.h>
#include <rpc/pmap_prot.h>
#include <rpc/pmap_rmt.h>
#include <rpc/rpc.h>
#include <rpc/svc.h>

#define INIT /**/
#define GETC() getchar()
#define PEEKC() 'x'
#define UNGETC(c) ungetc(c, stdin)
#define RETURN(ptr) return ptr
#define ERROR(val) return 0
#include <regexp.h>
#undef INIT
#undef GETC
#undef PEEKC
#undef UNGETC
#undef RETURN
#undef ERROR

/* Man page exists, but documented in the man page as having no
   prototype in glibc, or being deprecated: */

int arch_prctl(int, unsigned long);
caddr_t create_module(const char *, size_t);
int delete_module(const char *, int);
int get_kernel_syms(void *);
char *gets(char *s);
int init_module(void *, unsigned long, const char *);
int modify_ldt(int, void *, unsigned long);
long nfsservctl(int, void *, void *);
int pivot_root(const char *, const char *);
int query_module(const char *, int, void *, size_t, size_t);
int uselib(const char *);

void passwd2des(char *passwd, char *key);
int xencrypt(char *secret, char *passwd);
int xdecrypt(char *secret, char *passwd);

struct sigvec {
  void (*sv_handler)(int); /* Signal disposition */
  int    sv_mask;          /* Signals to be blocked in handler */
  int    sv_flags;         /* Flags */
};
int sigvec(int sig, const struct sigvec *vec, struct sigvec *ovec);


/* Copied from the glibc source: */
/* gmon/gmon.c */
void moncontrol(int);
/* gmon/sprofil.c */
int sprofil(struct prof *, int, struct timeval *, unsigned int);
/* include/netdb.h */
int ruserpass(const char *, const char **, const char **);
/* sunrpc/rpc_prot.c */
bool_t xdr_accepted_reply(XDR *xdrs, struct accepted_reply *ar);
bool_t xdr_rejected_reply(XDR *xdrs, struct rejected_reply *rr);
/* sunrpc/svc_simple.c */
int registerrpc(u_long prognum, u_long versnum, u_long procnum,
		char *(*progname) (char *), xdrproc_t inproc,
		xdrproc_t outproc);
/* sunrpc/authdes_prot.c */
bool_t xdr_authdes_cred (XDR *xdrs, struct authdes_cred *cred);
bool_t xdr_authdes_verf (XDR *xdrs, struct authdes_verf *verf);
/* sunrpc/svc_unix.c */
SVCXPRT * svcunixfd_create (int fd, u_int sendsize, u_int recvsize);
/* sunrpc/key_call.c */
int key_setnet (struct key_netstarg *arg);
/* sunrpc/svc_udp.c */
int svcudp_enablecache (SVCXPRT *transp, u_long size);
/* malloc/mcheck.c */
void tr_break(void);
/* sysdeps/unix/sysv/linux/sys/timex.h */
int ntp_gettimex (struct ntptimeval *__ntv);
/* misc/sstk.c */
void *sstk(int);
/* misc/stty.c */
int stty(int fd, const struct sgttyb *);


/* Defined only in assembly on x86_64: */
void mcount(void);

typedef long (*func)(long, long, long, long, long, long);

func funcs[] = {
    (func)syslog,
    (func)vsyslog,
    (func)openlog,
    (func)closelog,
    (func)setlogmask,
    (func)syscall,
    (func)daemon,
    (func)mmap,
    (func)munmap,
    (func)mprotect,
    (func)msync,
    (func)madvise,
    (func)mincore,
    (func)remap_file_pages,
    (func)mlock,
    (func)munlock,
    (func)mlockall,
    (func)munlockall,
    (func)hdestroy,
    (func)hsearch,
    (func)hcreate,
    (func)hcreate_r,
    (func)hdestroy_r,
    (func)hsearch_r,
    (func)tsearch,
    (func)tfind,
    (func)tdelete,
    (func)twalk,
    (func)tdestroy,
    (func)lsearch,
    (func)lfind,
    (func)vwarnx,
    (func)vwarn,
    (func)warn,
    (func)warnx,
    (func)verr,
    (func)verrx,
    (func)err,
    (func)errx,
    (func)error,
    (func)error_at_line,
    (func)ustat,
    (func)get_nprocs,
    (func)get_nprocs_conf,
    (func)get_phys_pages,
    (func)get_avphys_pages,
    (func)dirname,
    (func)getloadavg,
    (func)fgetxattr,
    (func)flistxattr,
    (func)fremovexattr,
    (func)fsetxattr,
    (func)getxattr,
    (func)listxattr,
    (func)lgetxattr,
    (func)llistxattr,
    (func)lremovexattr,
    (func)lsetxattr,
    (func)removexattr,
    (func)setxattr,
    (func)getauxval,
    (func)step,
    (func)advance,
    (func)setfsent,
    (func)getfsent,
    (func)getfsspec,
    (func)getfsfile,
    (func)endfsent,
    (func)revoke,
    (func)fcvt,
    (func)ecvt,
    (func)gcvt,
    (func)fcvt_r,
    (func)ecvt_r,
    (func)qfcvt,
    (func)qecvt,
    (func)qgcvt,
    (func)qfcvt_r,
    (func)qecvt_r,
    (func)ioperm,
    (func)iopl,
    (func)sysctl,
    (func)clone,
    (func)lseek,
    (func)umount,
    (func)umount2,
    (func)readahead,
    (func)setfsuid,
    (func)setfsgid,
    (func)gnu_dev_major,
    (func)gnu_dev_minor,
    (func)gnu_dev_makedev,
    (func)epoll_pwait,
    (func)signalfd,
    (func)eventfd,
    (func)eventfd_read,
    (func)eventfd_write,
    (func)prlimit,
    (func)arch_prctl,
    (func)modify_ldt,
    (func)fanotify_mark,
    (func)adjtimex,
    (func)capget,
    (func)capset,
    (func)clock_adjtime,
    (func)create_module,
    (func)delete_module,
    (func)epoll_create,
    (func)epoll_create1,
    (func)epoll_ctl,
    (func)epoll_wait,
    (func)get_kernel_syms,
    (func)init_module,
    (func)inotify_add_watch,
    (func)inotify_init,
    (func)inotify_init1,
    (func)inotify_rm_watch,
    (func)klogctl,
    (func)mount,
    (func)mremap,
    (func)nfsservctl,
    (func)personality,
    (func)pivot_root,
    (func)prctl,
    (func)query_module,
    (func)quotactl,
    (func)splice,
    (func)sysinfo,
    (func)tee,
    (func)unshare,
    (func)uselib,
    (func)vmsplice,
    (func)timerfd_create,
    (func)timerfd_settime,
    (func)timerfd_gettime,
    (func)fanotify_init,
    (func)name_to_handle_at,
    (func)open_by_handle_at,
    (func)setns,
    (func)process_vm_readv,
    (func)process_vm_writev,
    (func)bdflush,
    (func)accept,
    (func)bind,
    (func)connect,
    (func)getpeername,
    (func)getsockname,
    (func)getsockopt,
    (func)listen,
    (func)recv,
    (func)recvfrom,
    (func)recvmsg,
    (func)send,
    (func)sendmsg,
    (func)sendto,
    (func)setsockopt,
    (func)shutdown,
    (func)socket,
    (func)socketpair,
    (func)isfdtype,
    (func)sockatmark,
    (func)accept4,
    (func)recvmmsg,
    (func)sendmmsg,
    (func)ftok,
    (func)msgsnd,
    (func)msgrcv,
    (func)msgget,
    (func)msgctl,
    (func)semop,
    (func)semget,
    (func)semctl,
    (func)semtimedop,
    (func)shmat,
    (func)shmdt,
    (func)shmget,
    (func)shmctl,
    (func)moncontrol,
    (func)monstartup,
    (func)_mcleanup,
    (func)profil,
    (func)sprofil,
    (func)mcount,
    (func)wctrans,
    (func)towctrans,
    (func)towctrans_l,
    (func)iswalnum,
    (func)iswalpha,
    (func)iswblank,
    (func)iswcntrl,
    (func)iswdigit,
    (func)iswlower,
    (func)iswgraph,
    (func)iswprint,
    (func)iswpunct,
    (func)iswspace,
    (func)iswupper,
    (func)iswxdigit,
    (func)towlower,
    (func)towupper,
    (func)wctype,
    (func)iswctype,
    (func)iswalnum_l,
    (func)iswalpha_l,
    (func)iswblank_l,
    (func)iswcntrl_l,
    (func)iswdigit_l,
    (func)iswlower_l,
    (func)iswgraph_l,
    (func)iswprint_l,
    (func)iswpunct_l,
    (func)iswspace_l,
    (func)iswupper_l,
    (func)iswxdigit_l,
    (func)towlower_l,
    (func)towupper_l,
    (func)wctype_l,
    (func)iswctype_l,
    (func)wctrans_l,
    (func)getspent,
    (func)getspnam,
    (func)sgetspent,
    (func)fgetspent,
    (func)putspent,
    (func)setspent,
    (func)endspent,
    (func)getspent_r,
    (func)getspnam_r,
    (func)sgetspent_r,
    (func)fgetspent_r,
    (func)lckpwdf,
    (func)ulckpwdf,
    (func)getsgent,
    (func)getsgnam,
    (func)sgetsgent,
    (func)fgetsgent,
    (func)putsgent,
    (func)setsgent,
    (func)endsgent,
    (func)getsgent_r,
    (func)getsgnam_r,
    (func)sgetsgent_r,
    (func)fgetsgent_r,
    (func)argp_failure,
    (func)argp_help,
    (func)argp_state_help,
    (func)argp_error,
    (func)argp_parse,
    (func)argp_usage,
    (func)pthread_equal,
    (func)pthread_attr_destroy,
    (func)pthread_attr_init,
    (func)pthread_attr_getdetachstate,
    (func)pthread_attr_setdetachstate,
    (func)pthread_attr_getinheritsched,
    (func)pthread_attr_setinheritsched,
    (func)pthread_attr_getschedparam,
    (func)pthread_attr_setschedparam,
    (func)pthread_attr_getschedpolicy,
    (func)pthread_attr_setschedpolicy,
    (func)pthread_attr_getscope,
    (func)pthread_attr_setscope,
    (func)pthread_condattr_destroy,
    (func)pthread_condattr_init,
    (func)pthread_cond_broadcast,
    (func)pthread_cond_destroy,
    (func)pthread_cond_init,
    (func)pthread_cond_signal,
    (func)pthread_cond_wait,
    (func)pthread_cond_timedwait,
    (func)pthread_exit,
    (func)pthread_getschedparam,
    (func)pthread_setschedparam,
    (func)pthread_mutex_destroy,
    (func)pthread_mutex_init,
    (func)pthread_mutex_lock,
    (func)pthread_mutex_unlock,
    (func)pthread_self,
    (func)pthread_setcancelstate,
    (func)pthread_setcanceltype,
    (func)clock_getcpuclockid,
    (func)clock_getres,
    (func)clock_gettime,
    (func)clock_settime,
    (func)clock_nanosleep,
    (func)backtrace,
    (func)backtrace_symbols,
    (func)backtrace_symbols_fd,
    (func)htonl,
    (func)htons,
    (func)inet_lnaof,
    (func)inet_makeaddr,
    (func)inet_netof,
    (func)inet_ntoa,
    (func)inet_network,
    (func)gethostbyaddr,
    (func)gethostbyaddr_r,
    (func)gethostbyname,
    (func)gethostbyname2,
    (func)gethostbyname2_r,
    (func)gethostbyname_r,
    (func)gethostent,
    (func)sethostent,
    (func)endhostent,
    (func)gethostent_r,
    (func)getnetbyaddr,
    (func)getnetbyaddr_r,
    (func)getnetbyname,
    (func)getnetent,
    (func)setnetent,
    (func)endnetent,
    (func)getnetent_r,
    (func)getnetbyname_r,
    (func)getprotobynumber,
    (func)getprotobynumber_r,
    (func)getprotoent,
    (func)setprotoent,
    (func)endprotoent,
    (func)getprotoent_r,
    (func)getprotobyname,
    (func)getprotobyname_r,
    (func)getservbyname,
    (func)getservbyname_r,
    (func)getservbyport,
    (func)getservbyport_r,
    (func)getservent,
    (func)setservent,
    (func)endservent,
    (func)getservent_r,
    (func)getrpcent,
    (func)getrpcbyname,
    (func)getrpcbynumber,
    (func)setrpcent,
    (func)endrpcent,
    (func)getrpcent_r,
    (func)getrpcbyname_r,
    (func)getrpcbynumber_r,
    (func)ether_aton,
    (func)ether_aton_r,
    (func)ether_hostton,
    (func)ether_line,
    (func)ether_ntoa,
    (func)ether_ntoa_r,
    (func)ether_ntohost,
    (func)setnetgrent,
    (func)endnetgrent,
    (func)getnetgrent_r,
    (func)innetgr,
    (func)getnetgrent,
    (func)getnameinfo,
    (func)if_nametoindex,
    (func)if_freenameindex,
    (func)if_nameindex,
    (func)if_indextoname,
    (func)getifaddrs,
    (func)freeifaddrs,
    (func)getipv4sourcefilter,
    (func)setipv4sourcefilter,
    (func)getsourcefilter,
    (func)setsourcefilter,
    (func)rresvport_af,
    (func)rcmd_af,
    (func)rcmd,
    (func)rresvport,
    (func)ruserok_af,
    (func)ruserok,
    (func)iruserok_af,
    (func)iruserok,
    (func)rexec_af,
    (func)rexec,
    (func)ruserpass,
    (func)setaliasent,
    (func)endaliasent,
    (func)getaliasent_r,
    (func)getaliasent,
    (func)getaliasbyname,
    (func)getaliasbyname_r,
    (func)inet6_option_space,
    (func)inet6_option_init,
    (func)inet6_option_append,
    (func)inet6_option_alloc,
    (func)inet6_option_next,
    (func)inet6_option_find,
    (func)inet6_opt_init,
    (func)inet6_opt_append,
    (func)inet6_opt_finish,
    (func)inet6_opt_set_val,
    (func)inet6_opt_next,
    (func)inet6_opt_find,
    (func)inet6_opt_get_val,
    (func)inet6_rth_space,
    (func)inet6_rth_init,
    (func)inet6_rth_add,
    (func)inet6_rth_reverse,
    (func)inet6_rth_segments,
    (func)inet6_rth_getaddr,
    (func)herror,
    (func)hstrerror,
    (func)inet_addr,
    (func)inet_aton,
    (func)inet_ntop,
    (func)inet_pton,
    (func)inet_nsap_addr,
    (func)inet_nsap_ntoa,
    (func)authnone_create,
    (func)xdr_authunix_parms,
    (func)bindresvport,
    (func)clntraw_create,
    (func)callrpc,
    (func)_rpc_dtablesize,
    (func)getrpcport,
    (func)pmap_set,
    (func)pmap_unset,
    (func)pmap_getmaps,
    (func)xdr_pmap,
    (func)xdr_pmaplist,
    (func)xdr_rmtcallres,
    (func)xdr_rmtcall_args,
    (func)pmap_rmtcall,
    (func)clnt_broadcast,
    (func)xdr_rejected_reply,
    (func)xdr_accepted_reply,
    (func)xdr_opaque_auth,
    (func)xdr_des_block,
    (func)xdr_replymsg,
    (func)xdr_callhdr,
    (func)_seterr_reply,
    (func)xdr_callmsg,
    (func)_authenticate,
    (func)svcraw_create,
    (func)registerrpc,
    (func)xdr_float,
    (func)xdr_double,
    (func)xdrrec_create,
    (func)xdrrec_skiprecord,
    (func)xdrrec_eof,
    (func)xdrrec_endofrecord,
    (func)getpublickey,
    (func)getsecretkey,
    (func)xdr_authdes_cred,
    (func)xdr_authdes_verf,
    (func)xdr_keystatus,
    (func)xdr_keybuf,
    (func)xdr_netnamestr,
    (func)xdr_cryptkeyarg,
    (func)xdr_cryptkeyarg2,
    (func)xdr_cryptkeyres,
    (func)xdr_unixcred,
    (func)xdr_getcredres,
    (func)xdr_key_netstarg,
    (func)xdr_key_netstres,
    (func)rtime,
    (func)authdes_getucred,
    (func)clntunix_create,
    (func)svcunix_create,
    (func)svcunixfd_create,
    (func)cbc_crypt,
    (func)ecb_crypt,
    (func)des_setparity,
    (func)authdes_create,
    (func)authdes_pk_create,
    (func)authunix_create,
    (func)authunix_create_default,
    (func)clnt_create,
    (func)clnt_sperror,
    (func)clnt_perror,
    (func)clnt_sperrno,
    (func)clnt_perrno,
    (func)clnt_spcreateerror,
    (func)clnt_pcreateerror,
    (func)clnttcp_create,
    (func)clntudp_bufcreate,
    (func)clntudp_create,
    (func)get_myaddress,
    (func)key_setsecret,
    (func)key_secretkey_is_set,
    (func)key_encryptsession,
    (func)key_decryptsession,
    (func)key_encryptsession_pk,
    (func)key_decryptsession_pk,
    (func)key_gendes,
    (func)key_setnet,
    (func)key_get_conv,
    (func)user2netname,
    (func)host2netname,
    (func)getnetname,
    (func)netname2user,
    (func)netname2host,
    (func)pmap_getport,
    (func)xprt_register,
    (func)xprt_unregister,
    (func)svc_register,
    (func)svc_unregister,
    (func)svc_sendreply,
    (func)svcerr_noproc,
    (func)svcerr_decode,
    (func)svcerr_systemerr,
    (func)svcerr_auth,
    (func)svcerr_weakauth,
    (func)svcerr_noprog,
    (func)svcerr_progvers,
    (func)svc_getreq_common,
    (func)svc_getreqset,
    (func)svc_getreq_poll,
    (func)svc_getreq,
    (func)svctcp_create,
    (func)svcfd_create,
    (func)svcudp_bufcreate,
    (func)svcudp_create,
    (func)svcudp_enablecache,
    (func)xdr_array,
    (func)xdr_vector,
    (func)xdr_free,
    (func)xdr_void,
    (func)xdr_int,
    (func)xdr_u_int,
    (func)xdr_long,
    (func)xdr_u_long,
    (func)xdr_hyper,
    (func)xdr_u_hyper,
    (func)xdr_longlong_t,
    (func)xdr_u_longlong_t,
    (func)xdr_short,
    (func)xdr_u_short,
    (func)xdr_char,
    (func)xdr_u_char,
    (func)xdr_bool,
    (func)xdr_enum,
    (func)xdr_opaque,
    (func)xdr_bytes,
    (func)xdr_netobj,
    (func)xdr_union,
    (func)xdr_string,
    (func)xdr_wrapstring,
    (func)xdr_int64_t,
    (func)xdr_quad_t,
    (func)xdr_uint64_t,
    (func)xdr_u_quad_t,
    (func)xdr_int32_t,
    (func)xdr_uint32_t,
    (func)xdr_int16_t,
    (func)xdr_uint16_t,
    (func)xdr_int8_t,
    (func)xdr_uint8_t,
    (func)xdrmem_create,
    (func)xdr_reference,
    (func)xdr_pointer,
    (func)xdr_sizeof,
    (func)xdrstdio_create,
    (func)svc_exit,
    (func)svc_run,
    (func)passwd2des,
    (func)xencrypt,
    (func)xdecrypt,
    (func)isastream,
    (func)getmsg,
    (func)getpmsg,
    (func)putmsg,
    (func)putpmsg,
    (func)fattach,
    (func)fdetach,
    (func)posix_openpt,
    (func)getpt,
    (func)grantpt,
    (func)unlockpt,
    (func)ptsname_r,
    (func)ptsname,
    (func)getutent,
    (func)setutent,
    (func)getutent_r,
    (func)pututline,
    (func)endutent,
    (func)getutid,
    (func)getutline,
    (func)getutid_r,
    (func)getutline_r,
    (func)utmpname,
    (func)updwtmp,
    (func)getlogin,
    (func)getlogin_r,
    (func)setlogin,
    (func)setutxent,
    (func)getutxent,
    (func)endutxent,
    (func)getutxid,
    (func)getutxline,
    (func)pututxline,
    (func)utmpxname,
    (func)updwtmpx,
    (func)getutmp,
    (func)dl_iterate_phdr,
    (func)realpath,
    (func)sched_getaffinity,
    (func)sched_setaffinity,
    (func)regexec,
    (func)posix_spawn,
    (func)posix_spawnp,
    (func)nftw,
    (func)pthread_cond_broadcast,
    (func)pthread_cond_destroy,
    (func)pthread_cond_init,
    (func)pthread_cond_signal,
    (func)pthread_cond_wait,
    (func)pthread_cond_timedwait,
    (func)gnu_get_libc_release,
    (func)gnu_get_libc_version,
    (func)iconv_open,
    (func)iconv,
    (func)iconv_close,
    (func)setlocale,
    (func)localeconv,
    (func)nl_langinfo,
    (func)nl_langinfo_l,
    (func)newlocale,
    (func)duplocale,
    (func)freelocale,
    (func)uselocale,
    (func)isalnum,
    (func)isalpha,
    (func)iscntrl,
    (func)isdigit,
    (func)islower,
    (func)isgraph,
    (func)isprint,
    (func)ispunct,
    (func)isspace,
    (func)isupper,
    (func)isxdigit,
    (func)tolower,
    (func)toupper,
    (func)isblank,
    (func)_tolower,
    (func)_toupper,
    (func)toascii,
    (func)isascii,
    (func)isblank_l,
    (func)isalnum_l,
    (func)isalpha_l,
    (func)iscntrl_l,
    (func)isdigit_l,
    (func)islower_l,
    (func)isgraph_l,
    (func)isprint_l,
    (func)ispunct_l,
    (func)isspace_l,
    (func)isupper_l,
    (func)isxdigit_l,
    (func)tolower_l,
    (func)toupper_l,
    (func)isctype,
    (func)bindtextdomain,
    (func)bind_textdomain_codeset,
    (func)dcgettext,
    (func)dgettext,
    (func)gettext,
    (func)dcngettext,
    (func)dngettext,
    (func)ngettext,
    (func)textdomain,
    (func)catopen,
    (func)catgets,
    (func)catclose,
    (func)isinf,
    (func)isnan,
    (func)finite,
    (func)copysign,
    (func)modf,
    (func)scalbn,
    (func)frexp,
    (func)ldexp,
    (func)isinff,
    (func)isnanf,
    (func)finitef,
    (func)copysignf,
    (func)modff,
    (func)scalbnf,
    (func)frexpf,
    (func)ldexpf,
    (func)isinfl,
    (func)isnanl,
    (func)finitel,
    (func)copysignl,
    (func)modfl,
    (func)scalbnl,
    (func)frexpl,
    (func)ldexpl,
    (func)setjmp,
    (func)_setjmp,
    (func)longjmp,
    (func)signal,
    (func)raise,
    (func)killpg,
    (func)sigaction,
    (func)sigprocmask,
    (func)kill,
    (func)sigpending,
    (func)sigsuspend,
    (func)sigwait,
    (func)sigblock,
    (func)sigsetmask,
    (func)sigpause,
    (func)sigstack,
    (func)sigaltstack,
    (func)siginterrupt,
    (func)sigemptyset,
    (func)sigfillset,
    (func)sigaddset,
    (func)sigdelset,
    (func)sigismember,
    (func)sigreturn,
    (func)siggetmask,
    (func)sysv_signal,
    (func)sigisemptyset,
    (func)sigandset,
    (func)sigorset,
    (func)sigtimedwait,
    (func)sigwaitinfo,
    (func)sigqueue,
    (func)sighold,
    (func)sigrelse,
    (func)sigignore,
    (func)sigset,
    (func)atof,
    (func)atoi,
    (func)atol,
    (func)atoll,
    (func)abort,
    (func)bsearch,
    (func)qsort_r,
    (func)qsort,
    (func)getenv,
    (func)putenv,
    (func)setenv,
    (func)unsetenv,
    (func)clearenv,
    (func)secure_getenv,
    (func)exit,
    (func)on_exit,
    (func)quick_exit,
    (func)abs,
    (func)labs,
    (func)llabs,
    (func)div,
    (func)ldiv,
    (func)lldiv,
    (func)srand,
    (func)initstate,
    (func)setstate,
    (func)random,
    (func)setstate_r,
    (func)random_r,
    (func)srandom_r,
    (func)initstate_r,
    (func)rand,
    (func)rand_r,
    (func)drand48,
    (func)erand48,
    (func)lrand48,
    (func)nrand48,
    (func)mrand48,
    (func)jrand48,
    (func)srand48,
    (func)seed48,
    (func)lcong48,
    (func)drand48_r,
    (func)erand48_r,
    (func)lrand48_r,
    (func)nrand48_r,
    (func)mrand48_r,
    (func)jrand48_r,
    (func)srand48_r,
    (func)seed48_r,
    (func)lcong48_r,
    (func)strtol,
    (func)strtoul,
    (func)strtol_l,
    (func)strtoul_l,
    (func)strtof,
    (func)strtod,
    (func)strtold,
    (func)strtof_l,
    (func)strtod_l,
    (func)strtold_l,
    (func)system,
    (func)realpath,
    (func)canonicalize_file_name,
    (func)a64l,
    (func)l64a,
    (func)getsubopt,
    (func)strtoimax,
    (func)strtoumax,
    (func)getcontext,
    (func)setcontext,
    (func)makecontext,
    (func)swapcontext,
    (func)strfmon,
    (func)strfmon_l,
    (func)mblen,
    (func)mbstowcs,
    (func)mbtowc,
    (func)wcstombs,
    (func)wctomb,
    (func)wcstoimax,
    (func)wcstoumax,
    (func)rpmatch,
    (func)fmtmsg,
    (func)addseverity,
    (func)ctermid,
    (func)cuserid,
    (func)vfprintf,
    (func)vprintf,
    (func)register_printf_specifier,
    (func)register_printf_function,
    (func)parse_printf_format,
    (func)register_printf_modifier,
    (func)register_printf_type,
    (func)printf_size,
    (func)printf_size_info,
    (func)fprintf,
    (func)printf,
    (func)snprintf,
    (func)sprintf,
    (func)asprintf,
    (func)dprintf,
    (func)_IO_vfscanf,
    (func)vfscanf,
    (func)fscanf,
    (func)scanf,
    (func)sscanf,
    (func)perror,
    (func)psignal,
    (func)tmpfile,
    (func)tmpnam,
    (func)tmpnam_r,
    (func)tempnam,
    (func)getline,
    (func)getw,
    (func)putw,
    (func)remove,
    (func)rename,
    (func)renameat,
    (func)flockfile,
    (func)ftrylockfile,
    (func)funlockfile,
    (func)psiginfo,
    (func)vfwprintf,
    (func)vfwscanf,
    (func)fclose,
    (func)fdopen,
    (func)fflush,
    (func)fgetpos,
    (func)fgets,
    (func)fopen,
    (func)fopencookie,
    (func)fputs,
    (func)fread,
    (func)fsetpos,
    (func)ftell,
    (func)fwrite,
    (func)getdelim,
    (func)gets,
    (func)popen,
    (func)puts,
    (func)setbuffer,
    (func)setvbuf,
    (func)ungetc,
    (func)vsprintf,
    (func)vsscanf,
    (func)putchar,
    (func)putchar_unlocked,
    (func)clearerr,
    (func)feof,
    (func)ferror,
    (func)fileno,
    (func)fputc,
    (func)freopen,
    (func)fseek,
    (func)getc,
    (func)getchar,
    (func)open_memstream,
    (func)pclose,
    (func)putc,
    (func)rewind,
    (func)setbuf,
    (func)setlinebuf,
    (func)vasprintf,
    (func)vdprintf,
    (func)vscanf,
    (func)vsnprintf,
    (func)obstack_vprintf,
    (func)obstack_printf,
    (func)fcloseall,
    (func)fseeko,
    (func)ftello,
    (func)freopen64,
    (func)fmemopen,
    (func)clearerr_unlocked,
    (func)feof_unlocked,
    (func)ferror_unlocked,
    (func)fputc_unlocked,
    (func)getc_unlocked,
    (func)getchar_unlocked,
    (func)fflush_unlocked,
    (func)putc_unlocked,
    (func)_IO_peekc_locked,
    (func)fread_unlocked,
    (func)fwrite_unlocked,
    (func)fgets_unlocked,
    (func)fputs_unlocked,
    (func)swprintf,
    (func)vswprintf,
    (func)vswscanf,
    (func)swscanf,
    (func)open_wmemstream,
    (func)fputwc,
    (func)fputwc_unlocked,
    (func)getwc,
    (func)getwc_unlocked,
    (func)getwchar,
    (func)getwchar_unlocked,
    (func)fgetws,
    (func)fgetws_unlocked,
    (func)fputws,
    (func)fputws_unlocked,
    (func)ungetwc,
    (func)putwc,
    (func)putwc_unlocked,
    (func)putwchar,
    (func)putwchar_unlocked,
    (func)fwprintf,
    (func)vwprintf,
    (func)wprintf,
    (func)wscanf,
    (func)fwscanf,
    (func)vwscanf,
    (func)fwide,
    (func)malloc,
    (func)malloc_get_state,
    (func)free,
    (func)realloc,
    (func)memalign,
    (func)calloc,
    (func)malloc_usable_size,
    (func)mallopt,
    (func)malloc_set_state,
    (func)valloc,
    (func)pvalloc,
    (func)malloc_trim,
    (func)mallinfo,
    (func)malloc_stats,
    (func)posix_memalign,
    (func)malloc_info,
    (func)mcheck_check_all,
    (func)mcheck,
    (func)mcheck_pedantic,
    (func)mprobe,
    (func)tr_break,
    (func)mtrace,
    (func)muntrace,
    (func)strcoll,
    (func)strverscmp,
    (func)strdup,
    (func)strndup,
    (func)strerror,
    (func)strerror_r,
    (func)strlen,
    (func)strnlen,
    (func)rindex,
    (func)strsignal,
    (func)strtok,
    (func)strtok_r,
    (func)strxfrm,
    (func)memchr,
    (func)bzero,
    (func)memset,
    (func)bcopy,
    (func)ffs,
    (func)ffsl,
    (func)memccpy,
    (func)strsep,
    (func)swab,
    (func)strfry,
    (func)memfrob,
    (func)memmem,
    (func)rawmemchr,
    (func)strchrnul,
    (func)argz_append,
    (func)argz_add,
    (func)argz_count,
    (func)argz_create,
    (func)argz_create_sep,
    (func)argz_next,
    (func)argz_delete,
    (func)argz_extract,
    (func)argz_insert,
    (func)argz_stringify,
    (func)argz_add_sep,
    (func)argz_replace,
    (func)basename,
    (func)strcoll_l,
    (func)strxfrm_l,
    (func)memrchr,
    (func)strerror_l,
    (func)envz_entry,
    (func)envz_get,
    (func)envz_remove,
    (func)envz_add,
    (func)envz_merge,
    (func)envz_strip,
    (func)wmemcpy,
    (func)wmemset,
    (func)wcscat,
    (func)wcschr,
    (func)wcscmp,
    (func)wcscspn,
    (func)wcsdup,
    (func)wcslen,
    (func)wcsncat,
    (func)wcsncmp,
    (func)wcsncpy,
    (func)wcspbrk,
    (func)wcsrchr,
    (func)wcsspn,
    (func)wcstok,
    (func)wcsstr,
    (func)wmemchr,
    (func)wmemmove,
    (func)wcpcpy,
    (func)wcpncpy,
    (func)wmempcpy,
    (func)btowc,
    (func)wctob,
    (func)mbsinit,
    (func)mbrlen,
    (func)mbrtowc,
    (func)wcrtomb,
    (func)mbsrtowcs,
    (func)wcsrtombs,
    (func)mbsnrtowcs,
    (func)wcsnrtombs,
    (func)wcsnlen,
    (func)wcschrnul,
    (func)wcstol,
    (func)wcstoul,
    (func)wcstod,
    (func)wcstold,
    (func)wcstof,
    (func)wcstol_l,
    (func)wcstoul_l,
    (func)wcstod_l,
    (func)wcstold_l,
    (func)wcstof_l,
    (func)wcscoll,
    (func)wcsxfrm,
    (func)wcwidth,
    (func)wcswidth,
    (func)wcscoll_l,
    (func)wcsxfrm_l,
    (func)wcscasecmp,
    (func)wcsncasecmp,
    (func)wcscasecmp_l,
    (func)wcsncasecmp_l,
    (func)mbrtoc16,
    (func)c16rtomb,
    (func)asctime_r,
    (func)asctime,
    (func)clock,
    (func)ctime,
    (func)ctime_r,
    (func)difftime,
    (func)gmtime_r,
    (func)gmtime,
    (func)localtime_r,
    (func)localtime,
    (func)mktime,
    (func)settimeofday,
    (func)adjtime,
    (func)tzset,
    (func)getitimer,
    (func)setitimer,
    (func)stime,
    (func)dysize,
    (func)timegm,
    (func)ftime,
    (func)getdate_r,
    (func)getdate,
    (func)strptime,
    (func)strptime_l,
    (func)strftime,
    (func)strftime_l,
    (func)timespec_get,
    (func)wcsftime,
    (func)wcsftime_l,
    (func)ntp_gettime,
    (func)ntp_gettimex,
    (func)opendir,
    (func)closedir,
    (func)readdir,
    (func)readdir_r,
    (func)rewinddir,
    (func)seekdir,
    (func)telldir,
    (func)scandir,
    (func)alphasort,
    (func)versionsort,
    (func)dirfd,
    (func)fdopendir,
    (func)scandirat,
    (func)getdirentries,
    (func)fgetgrent,
    (func)getgrouplist,
    (func)initgroups,
    (func)setgroups,
    (func)getgrent,
    (func)getgrgid,
    (func)getgrnam,
    (func)putgrent,
    (func)setgrent,
    (func)endgrent,
    (func)getgrent_r,
    (func)getgrgid_r,
    (func)getgrnam_r,
    (func)fgetgrent_r,
    (func)fgetpwent,
    (func)getpw,
    (func)putpwent,
    (func)getpwent,
    (func)getpwnam,
    (func)getpwuid,
    (func)setpwent,
    (func)endpwent,
    (func)getpwent_r,
    (func)getpwnam_r,
    (func)getpwuid_r,
    (func)fgetpwent_r,
    (func)uname,
    (func)times,
    (func)wait,
    (func)waitpid,
    (func)wait3,
    (func)wait4,
    (func)waitid,
    (func)alarm,
    (func)sleep,
    (func)pause,
    (func)nanosleep,
    (func)fork,
    (func)vfork,
    (func)_Exit,
    (func)execve,
    (func)fexecve,
    (func)execv,
    (func)execle,
    (func)execl,
    (func)execvp,
    (func)execlp,
    (func)execvpe,
    (func)getpid,
    (func)getppid,
    (func)getuid,
    (func)geteuid,
    (func)getgid,
    (func)getegid,
    (func)getgroups,
    (func)setuid,
    (func)setgid,
    (func)group_member,
    (func)getpgid,
    (func)setpgid,
    (func)getpgrp,
    (func)setpgrp,
    (func)getsid,
    (func)setsid,
    (func)getresuid,
    (func)getresgid,
    (func)setresuid,
    (func)setresgid,
    (func)pathconf,
    (func)sysconf,
    (func)fpathconf,
    (func)globfree,
    (func)glob,
    (func)glob_pattern_p,
    (func)fnmatch,
    (func)confstr,
    (func)getopt,
    (func)getopt_long,
    (func)getopt_long_only,
    (func)sched_setparam,
    (func)sched_getparam,
    (func)sched_setscheduler,
    (func)sched_getscheduler,
    (func)sched_yield,
    (func)sched_get_priority_max,
    (func)sched_get_priority_min,
    (func)sched_rr_get_interval,
    (func)sched_getaffinity,
    (func)sched_setaffinity,
    (func)pread,
    (func)pwrite,
    (func)posix_madvise,
    (func)getaddrinfo,
    (func)freeaddrinfo,
    (func)gai_strerror,
    (func)re_compile_pattern,
    (func)re_set_syntax,
    (func)re_compile_fastmap,
    (func)regcomp,
    (func)regerror,
    (func)regfree,
    (func)re_comp,
    (func)regexec,
    (func)re_match,
    (func)re_search,
    (func)re_match_2,
    (func)re_search_2,
    (func)re_set_registers,
    (func)re_exec,
    (func)posix_spawn_file_actions_init,
    (func)posix_spawn_file_actions_destroy,
    (func)posix_spawn_file_actions_addclose,
    (func)posix_spawn_file_actions_addopen,
    (func)posix_spawn_file_actions_adddup2,
    (func)posix_spawnattr_init,
    (func)posix_spawnattr_destroy,
    (func)posix_spawnattr_getsigdefault,
    (func)posix_spawnattr_setsigdefault,
    (func)posix_spawnattr_getflags,
    (func)posix_spawnattr_setflags,
    (func)posix_spawnattr_getpgroup,
    (func)posix_spawnattr_setpgroup,
    (func)posix_spawn,
    (func)posix_spawnp,
    (func)posix_spawnattr_getsigmask,
    (func)posix_spawnattr_getschedpolicy,
    (func)posix_spawnattr_getschedparam,
    (func)posix_spawnattr_setsigmask,
    (func)posix_spawnattr_setschedpolicy,
    (func)posix_spawnattr_setschedparam,
    (func)wordfree,
    (func)wordexp,
    (func)sched_getcpu,
    (func)utime,
    (func)mkfifo,
    (func)mkfifoat,
    (func)statfs,
    (func)fstatfs,
    (func)statvfs,
    (func)fstatvfs,
    (func)umask,
    (func)chmod,
    (func)fchmod,
    (func)fchmodat,
    (func)mkdir,
    (func)mkdirat,
    (func)open,
    (func)openat,
    (func)read,
    (func)write,
    (func)access,
    (func)eaccess,
    (func)faccessat,
    (func)fcntl,
    (func)flock,
    (func)lockf,
    (func)close,
    (func)dup,
    (func)dup2,
    (func)dup3,
    (func)pipe,
    (func)pipe2,
    (func)creat,
    (func)chdir,
    (func)fchdir,
    (func)getcwd,
    (func)getwd,
    (func)get_current_dir_name,
    (func)chown,
    (func)fchown,
    (func)lchown,
    (func)fchownat,
    (func)ttyname,
    (func)ttyname_r,
    (func)isatty,
    (func)link,
    (func)linkat,
    (func)symlink,
    (func)symlinkat,
    (func)readlink,
    (func)readlinkat,
    (func)unlink,
    (func)unlinkat,
    (func)rmdir,
    (func)poll,
    (func)ppoll,
    (func)posix_fadvise,
    (func)posix_fallocate,
    (func)sendfile,
    (func)utimensat,
    (func)futimens,
    (func)lchmod,
    (func)ftw,
    (func)nftw,
    (func)fts_open,
    (func)fts_close,
    (func)fts_read,
    (func)fts_set,
    (func)fts_children,
    (func)sync_file_range,
    (func)fallocate,
    (func)cfgetospeed,
    (func)cfgetispeed,
    (func)cfsetospeed,
    (func)cfsetispeed,
    (func)cfsetspeed,
    (func)tcsetattr,
    (func)tcgetattr,
    (func)tcgetpgrp,
    (func)tcsetpgrp,
    (func)tcdrain,
    (func)tcflow,
    (func)tcflush,
    (func)tcsendbreak,
    (func)cfmakeraw,
    (func)tcgetsid,
    (func)getrlimit,
    (func)setrlimit,
    (func)getrusage,
    (func)ulimit,
    (func)vlimit,
    (func)vtimes,
    (func)getpriority,
    (func)setpriority,
    (func)nice,
    (func)brk,
    (func)sbrk,
    (func)sstk,
    (func)ioctl,
    (func)readv,
    (func)writev,
    (func)preadv,
    (func)pwritev,
    (func)setreuid,
    (func)setregid,
    (func)seteuid,
    (func)setegid,
    (func)getpagesize,
    (func)getdtablesize,
    (func)gethostname,
    (func)sethostname,
    (func)getdomainname,
    (func)setdomainname,
    (func)select,
    (func)pselect,
    (func)acct,
    (func)chroot,
    (func)fsync,
    (func)sync,
    (func)fdatasync,
    (func)syncfs,
    (func)reboot,
    (func)gethostid,
    (func)sethostid,
    (func)vhangup,
    (func)swapon,
    (func)swapoff,
    (func)mktemp,
    (func)mkstemp,
    (func)mkdtemp,
    (func)mkostemp,
    (func)mkstemps,
    (func)mkostemps,
    (func)ualarm,
    (func)usleep,
    (func)gtty,
    (func)stty,
    (func)ptrace,
    (func)getmntent,
    (func)setmntent,
    (func)endmntent,
    (func)getmntent_r,
    (func)addmntent,
    (func)hasmntopt,
    (func)utimes,
    (func)lutimes,
    (func)futimes,
    (func)futimesat,
    (func)truncate,
    (func)ftruncate,
    (func)insque,
    (func)remque,
    (func)getttyent,
    (func)getttynam,
    (func)setttyent,
    (func)endttyent,
    (func)getusershell,
    (func)endusershell,
    (func)setusershell,
    (func)getpass,
    (func)ttyslot,
    /*(func)chflags, stub*/
    /*(func)fchflags, stub */
    /*(func)_nss_files_parse_spent, _ */
    /*(func)_nss_files_parse_sgent, _ */
    /* (func)_dl_addr, _ */
    /* (func)_dl_mcount_wrapper, _ */
    /* (func)_dl_mcount_wrapper_check, _ */
    /* (func)_dl_vsym, _ */
    /* (func)_dl_sym, _ */
    /*(func)sigvec, not in 2.21 */
    /*(func)_IO_file_doallocate, _ */
    /*(func)_IO_getline_info, _ */
    /*(func)_IO_getline, _ */
    /*(func)_IO_padn, _ */
    /*(func)_IO_proc_close, _ */
    /*(func)_IO_proc_open, _ */
    /*(func)_IO_seekoff, _*/
    /*(func)_IO_seekpos, _*/
    /*(func)_IO_least_wmarker,
     *    (func)_IO_switch_to_main_wget_area,
*    (func)_IO_switch_to_wbackup_area,
*    (func)_IO_wsetb,
*    (func)_IO_wdefault_pbackfail,
*    (func)_IO_wdefault_finish,
*    (func)_IO_wdefault_uflow,
*    (func)_IO_wdefault_xsputn,
*    (func)_IO_wdefault_xsgetn,
*    (func)_IO_wdoallocbuf,
*    (func)_IO_wdefault_doallocate,
*    (func)_IO_switch_to_wget_mode,
*    (func)_IO_free_wbackup_area,
*    (func)_IO_sputbackwc,
 *   (func)_IO_sungetwc,
*    (func)_IO_adjust_wcolumn,
*    (func)_IO_init_wmarker,
*    (func)_IO_wmarker_delta,
*    (func)_IO_seekwmark,
*    (func)_IO_unsave_wmarkers,
*    (func)_IO_wfile_underflow,
*    (func)_IO_wfile_seekoff,
*    (func)_IO_wdo_write,
*    (func)_IO_wfile_overflow,
*    (func)_IO_wfile_sync,
*    (func)_IO_wfile_xsputn, _ */
    /*(func)_IO_file_sync,
 *   (func)_IO_file_close,
*    (func)_IO_file_setbuf,
*    (func)_IO_file_seekoff,
*    (func)_IO_file_seek,
*    (func)_IO_file_stat,
*    (func)_IO_file_write,
*    (func)_IO_file_read,
*    (func)_IO_file_xsputn,
 *   (func)_IO_file_init,
*    (func)_IO_file_close_it,
 *   (func)_IO_file_finish,
*    (func)_IO_file_open,
  *  (func)_IO_file_fopen,
   * (func)_IO_file_attach,
 *   (func)_IO_do_write,
  *  (func)_IO_file_underflow,
 *   (func)_IO_file_overflow,
*    (func)_IO_un_link,
*    (func)_IO_link_in,
*    (func)_IO_switch_to_get_mode,
*    (func)_IO_free_backup_area,
*    (func)_IO_setb,
 *   (func)_IO_doallocbuf,
*    (func)_IO_default_uflow,
*    (func)_IO_default_xsputn,
*    (func)_IO_sgetn,
*    (func)_IO_default_xsgetn,
*    (func)_IO_default_doallocate,
*    (func)_IO_init,
*    (func)_IO_default_finish,
*    (func)_IO_sputbackc,
*    (func)_IO_sungetc,
*    (func)_IO_adjust_column,
*    (func)_IO_flush_all,
*    (func)_flushlbf,
*    (func)_IO_init_marker,
*    (func)_IO_remove_marker,
*    (func)_IO_marker_difference,
*    (func)_IO_marker_delta,
*    (func)_IO_seekmark,
*    (func)_IO_unsave_markers,
*    (func)_IO_default_pbackfail,
*    (func)_IO_iter_begin,
*    (func)_IO_iter_end,
*    (func)_IO_iter_next,
*    (func)_IO_iter_file,
*    (func)_IO_list_lock,
*    (func)_IO_list_unlock,
*    (func)_IO_list_resetlock,
*    (func)_IO_str_underflow,
*    (func)_IO_str_overflow,
*    (func)_IO_str_pbackfail,
*    (func)_IO_str_init_static,
*    (func)_IO_str_init_readonly,
*    (func)_IO_str_seekoff, _ */
/*    (func)_obstack_begin,
 *   (func)_obstack_begin_1,
 *   (func)_obstack_newchunk,
 *   (func)_obstack_allocated_p, _ */
 *   (func)obstack_free,
    /*(func)_obstack_memory_used, _*/
    /*(func)_nss_files_parse_grent, _ */
    /*(func)_nss_files_parse_pwent, _*/
};

int main(int argc, char **argv) {
    long args[6] = {0, 0, 0, 0, 0, 0};
    int i;
    int fn_num;
    if (argc < 2 || argc > 7) {
	fprintf(stderr, "Usage: ptrs fnnum [0-6 args]\n");
	exit(1);
    }
    fn_num = atoi(argv[1]);
    for (i = 0; i < 6 && i + 2 < argc; i++) {
	char *s = argv[i + 2];
	if (isdigit(s[0])) {
	    args[i] = atol(s);
	} else {
	    args[i] = (long)s;
	}
    }
    (funcs[fn_num])(args[0], args[1], args[2], args[3], args[4], args[5]);
    /*(funcs[862])((long)"Hello, world!", 0, 0, 0, 0, 0);*/
    return 0;
}
