/* Generated by CIL v. 1.7.0 */
/* print_CIL_Input is false */

union _1_f2_$node;
struct _IO_FILE;
struct _IO_marker;
struct timeval;
enum _1_f2_$op;
extern  __attribute__((__nothrow__, __noreturn__)) void ( __attribute__((__leaf__)) exit)(int __status ) ;
enum _1_f2_$op {
    _1_f2__load_unsigned_char$left_STA_0$result_STA_0 = 132,
    _1_f2__formal$result_STA_0$value_LIT_0 = 191,
    _1_f2__branchIfTrue$expr_STA_0$label_LAB_0 = 201,
    _1_f2__Ge_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 175,
    _1_f2__label$label_LAB_0 = 146,
    _1_f2__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 1,
    _1_f2__store_unsigned_int$right_STA_0$left_STA_1 = 123,
    _1_f2__load_void_star$left_STA_0$result_STA_0 = 61,
    _1_f2__goto$label_LAB_0 = 235,
    _1_f2__load_int$left_STA_0$result_STA_0 = 7,
    _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0 = 37,
    _1_f2__return_long$expr_STA_0 = 195,
    _1_f2__convert_int2unsigned_long$left_STA_0$result_STA_0 = 4,
    _1_f2__constant_int$result_STA_0$value_LIT_0 = 239,
    _1_f2__Shiftrt_unsigned_int_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1 = 131,
    _1_f2__Neg_unsigned_int2unsigned_int$left_STA_0$result_STA_0 = 84,
    _1_f2__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1 = 124,
    _1_f2__load_unsigned_int$left_STA_0$result_STA_0 = 149,
    _1_f2__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 134,
    _1_f2__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1 = 211,
    _1_f2__convert_unsigned_int2long$left_STA_0$result_STA_0 = 58,
    _1_f2__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 236,
    _1_f2__BAnd_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1 = 56,
    _1_f2__convert_unsigned_char2unsigned_int$left_STA_0$result_STA_0 = 49,
    _1_f2__BXor_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1 = 157,
    _1_f2__local$result_STA_0$value_LIT_0 = 158,
    _1_f2__constant_unsigned_long$result_STA_0$value_LIT_0 = 13,
    _1_f2__store_int$left_STA_0$right_STA_1 = 253
} ;
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) strerror)(int __errnum ) ;
extern int fclose(void *stream ) ;
int old_f2(int a )  __attribute__((__annotate__("fla"), __annotate__("bcf"), __annotate__("sub"))) ;
int old_f1(int a ) ;
typedef long __off_t;
extern  __attribute__((__nothrow__)) long ( __attribute__((__nonnull__(1), __leaf__)) atol)(char const   *__nptr )  __attribute__((__pure__)) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
typedef void _IO_lock_t;
typedef long __off64_t;
typedef unsigned long size_t;
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   void *__pad1 ;
   void *__pad2 ;
   void *__pad3 ;
   void *__pad4 ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
int compare(long *r1p , long *r2p , long a0 , long a1 , long a2 , long a3 , long a4 ,
            long a5 ) ;
extern int raise(int sig ) ;
extern void abort() ;
typedef struct _IO_FILE FILE;
extern int fflush(FILE *__stream ) ;
void global_arg0_i$nit(void) ;
extern void *malloc(unsigned long size ) ;
void global_arg3_i$nit(void) ;
void fuzz_start(void) ;
extern int rand() ;
extern struct _IO_FILE *stdin ;
long f2(int bogus___2 , int bogus___1 , int len , unsigned char *message ) ;
long f1(unsigned char *message , int len ) ;
extern unsigned long strlen(char const   *s ) ;
int main(int argc , char **argv ) ;
union _1_f2_$node {
   void *_void_star ;
   unsigned long _unsigned_long ;
   long _long ;
   unsigned int _unsigned_int ;
   int _int ;
   unsigned char _unsigned_char ;
};
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int gettimeofday(struct timeval *tv , void *tz  , ...) ;
void megaInit(void) ;
extern int fscanf(FILE * __restrict  __stream , char const   * __restrict  __format 
                  , ...)  __asm__("__isoc99_fscanf")  ;
extern int printf(char const   * __restrict  __format  , ...) ;
extern int scanf(char const   *format  , ...) ;
extern float strtof(char const   *str , char const   *endptr ) ;
void global_arg1_i$nit(void) ;
extern unsigned long strnlen(char const   *s , unsigned long maxlen ) ;
long global_arg5 ;
extern double strtod(char const   *str , char const   *endptr ) ;
long global_arg4 ;
unsigned char _1_f2_$array[1][269]  = { {        _1_f2__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__store_int$left_STA_0$right_STA_1,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_f2__store_unsigned_int$right_STA_0$left_STA_1,        _1_f2__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__formal$result_STA_0$value_LIT_0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__load_int$left_STA_0$result_STA_0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__load_int$left_STA_0$result_STA_0,        _1_f2__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _1_f2__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__goto$label_LAB_0,        (unsigned char)204, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)24,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__load_void_star$left_STA_0$result_STA_0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)16, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_int$left_STA_0$result_STA_0, 
            _1_f2__convert_int2unsigned_long$left_STA_0$result_STA_0,        _1_f2__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1,        _1_f2__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1, 
            _1_f2__load_unsigned_char$left_STA_0$result_STA_0,        _1_f2__convert_unsigned_char2unsigned_int$left_STA_0$result_STA_0,        _1_f2__store_unsigned_int$right_STA_0$left_STA_1,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)20,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)24,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_f2__BXor_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_f2__store_unsigned_int$right_STA_0$left_STA_1,        _1_f2__constant_int$result_STA_0$value_LIT_0,        (unsigned char)7, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)28,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__store_int$left_STA_0$right_STA_1,        _1_f2__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)28, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_int$left_STA_0$result_STA_0, 
            _1_f2__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__Ge_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_f2__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)14, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__goto$label_LAB_0,        (unsigned char)82,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__BAnd_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1,        _1_f2__Neg_unsigned_int2unsigned_int$left_STA_0$result_STA_0,        _1_f2__store_unsigned_int$right_STA_0$left_STA_1, 
            _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)131, 
            (unsigned char)184,        (unsigned char)237,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)32, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_f2__BAnd_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1,        _1_f2__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)20, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0, 
            _1_f2__Shiftrt_unsigned_int_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_f2__BXor_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_f2__store_unsigned_int$right_STA_0$left_STA_1,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)28,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__load_int$left_STA_0$result_STA_0,        _1_f2__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_f2__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)28,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__store_int$left_STA_0$right_STA_1,        _1_f2__goto$label_LAB_0,        (unsigned char)160,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_f2__goto$label_LAB_0,        (unsigned char)155, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_f2__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)16,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__load_int$left_STA_0$result_STA_0,        _1_f2__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1,        _1_f2__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_f2__store_int$left_STA_0$right_STA_1,        _1_f2__goto$label_LAB_0,        (unsigned char)37,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_f2__goto$label_LAB_0,        (unsigned char)32, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0, 
            (unsigned char)255,        (unsigned char)255,        (unsigned char)255,        (unsigned char)255, 
            _1_f2__local$result_STA_0$value_LIT_0,        (unsigned char)20,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_f2__load_unsigned_int$left_STA_0$result_STA_0,        _1_f2__BXor_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1,        _1_f2__convert_unsigned_int2long$left_STA_0$result_STA_0, 
            _1_f2__return_long$expr_STA_0}};
void global_arg4_i$nit(void) ;
struct _IO_marker {
   struct _IO_marker *_next ;
   struct _IO_FILE *_sbuf ;
   int _pos ;
};
long wrap_f2(long a0 , long a1 ) ;
long global_arg3 ;
long global_arg2 ;
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes ) ;
long global_arg1 ;
extern void signal(int sig , void *func ) ;
extern struct _IO_FILE *stderr ;
long global_arg0 ;
extern  __attribute__((__nothrow__)) int *( __attribute__((__leaf__)) __errno_location)(void)  __attribute__((__const__)) ;
char const   *_1_f2_$strings  =    "";
extern int fprintf(FILE * __restrict  __stream , char const   * __restrict  __format 
                   , ...) ;
extern  __attribute__((__nothrow__)) unsigned short const   **( __attribute__((__leaf__)) __ctype_b_loc)(void)  __attribute__((__const__)) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned long maxlen ) ;
void global_arg2_i$nit(void) ;
void global_arg5_i$nit(void) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned long size ) ;
extern struct _IO_FILE *stdout ;
void global_arg2_i$nit(void) 
{ 


  {
  global_arg2 = 0L;
}
}
long f1(unsigned char *message , int len ) 
{ 
  int i ;
  int j ;
  unsigned int byte ;
  unsigned int crc ;
  unsigned int mask ;

  {
  i = 0;
  crc = 4294967295U;
  while (i < len) {
    byte = (unsigned int )*(message + i);
    crc ^= byte;
    j = 7;
    while (j >= 0) {
      mask = - (crc & 1U);
      crc = (crc >> 1) ^ (3988292384U & mask);
      j --;
    }
    i ++;
  }
  return ((long )(~ crc));
}
}
long f2(int bogus___2 , int bogus___1 , int len , unsigned char *message ) 
{ 
  char _1_f2_$locals[36] ;
  union _1_f2_$node _1_f2_$stack[1][32] ;
  union _1_f2_$node *_1_f2_$sp[1] ;
  unsigned char *_1_f2_$pc[1] ;

  {
  _1_f2_$sp[0] = _1_f2_$stack[0];
  _1_f2_$pc[0] = _1_f2_$array[0];
  while (1) {
    switch (*(_1_f2_$pc[0])) {
    case _1_f2__local$result_STA_0$value_LIT_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 1)->_void_star = (void *)(_1_f2_$locals + *((int *)_1_f2_$pc[0]));
    (_1_f2_$sp[0]) ++;
    _1_f2_$pc[0] += 4;
    break;
    case _1_f2__load_unsigned_char$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_unsigned_char = *((unsigned char *)(_1_f2_$sp[0] + 0)->_void_star);
    break;
    case _1_f2__goto$label_LAB_0: 
    (_1_f2_$pc[0]) ++;
    _1_f2_$pc[0] += *((int *)_1_f2_$pc[0]);
    break;
    case _1_f2__store_int$left_STA_0$right_STA_1: 
    (_1_f2_$pc[0]) ++;
    *((int *)(_1_f2_$sp[0] + 0)->_void_star) = (_1_f2_$sp[0] + -1)->_int;
    _1_f2_$sp[0] += -2;
    break;
    case _1_f2__load_int$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_int = *((int *)(_1_f2_$sp[0] + 0)->_void_star);
    break;
    case _1_f2__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_f2_$pc[0]) ++;
    if ((_1_f2_$sp[0] + 0)->_int) {
      _1_f2_$pc[0] += *((int *)_1_f2_$pc[0]);
    } else {
      _1_f2_$pc[0] += 4;
    }
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__return_long$expr_STA_0: 
    (_1_f2_$pc[0]) ++;
    return ((_1_f2_$sp[0] + 0)->_long);
    break;
    case _1_f2__BXor_unsigned_int_unsigned_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_unsigned_int = (_1_f2_$sp[0] + 0)->_unsigned_int ^ (_1_f2_$sp[0] + -1)->_unsigned_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__Lt_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_int = (_1_f2_$sp[0] + 0)->_int < (_1_f2_$sp[0] + -1)->_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__BAnd_unsigned_int_unsigned_int2unsigned_int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_unsigned_int = (_1_f2_$sp[0] + -1)->_unsigned_int & (_1_f2_$sp[0] + 0)->_unsigned_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__IndexPI_void_star_unsigned_long2void_star$right_STA_0$result_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_void_star = (_1_f2_$sp[0] + -1)->_void_star + (_1_f2_$sp[0] + 0)->_unsigned_long;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__label$label_LAB_0: 
    (_1_f2_$pc[0]) ++;
    break;
    case _1_f2__Neg_unsigned_int2unsigned_int$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_unsigned_int = - (_1_f2_$sp[0] + 0)->_unsigned_int;
    break;
    case _1_f2__convert_unsigned_char2unsigned_int$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_unsigned_int = (unsigned int )(_1_f2_$sp[0] + 0)->_unsigned_char;
    break;
    case _1_f2__MinusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_int = (_1_f2_$sp[0] + -1)->_int - (_1_f2_$sp[0] + 0)->_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__constant_unsigned_int$result_STA_0$value_LIT_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 1)->_unsigned_int = *((unsigned int *)_1_f2_$pc[0]);
    (_1_f2_$sp[0]) ++;
    _1_f2_$pc[0] += 4;
    break;
    case _1_f2__formal$result_STA_0$value_LIT_0: 
    (_1_f2_$pc[0]) ++;
    switch (*((int *)_1_f2_$pc[0])) {
    case 0: 
    (_1_f2_$sp[0] + 1)->_void_star = (void *)(& len);
    break;
    case 1: 
    (_1_f2_$sp[0] + 1)->_void_star = (void *)(& message);
    break;
    }
    (_1_f2_$sp[0]) ++;
    _1_f2_$pc[0] += 4;
    break;
    case _1_f2__load_void_star$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_void_star = *((void **)(_1_f2_$sp[0] + 0)->_void_star);
    break;
    case _1_f2__convert_unsigned_int2long$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_long = (long )(_1_f2_$sp[0] + 0)->_unsigned_int;
    break;
    case _1_f2__constant_int$result_STA_0$value_LIT_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 1)->_int = *((int *)_1_f2_$pc[0]);
    (_1_f2_$sp[0]) ++;
    _1_f2_$pc[0] += 4;
    break;
    case _1_f2__store_unsigned_int$right_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    *((unsigned int *)(_1_f2_$sp[0] + -1)->_void_star) = (_1_f2_$sp[0] + 0)->_unsigned_int;
    _1_f2_$sp[0] += -2;
    break;
    case _1_f2__load_unsigned_int$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_unsigned_int = *((unsigned int *)(_1_f2_$sp[0] + 0)->_void_star);
    break;
    case _1_f2__Shiftrt_unsigned_int_int2unsigned_int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_unsigned_int = (_1_f2_$sp[0] + 0)->_unsigned_int >> (_1_f2_$sp[0] + -1)->_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__Ge_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_int = (_1_f2_$sp[0] + -1)->_int >= (_1_f2_$sp[0] + 0)->_int;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__convert_int2unsigned_long$left_STA_0$result_STA_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 0)->_unsigned_long = (unsigned long )(_1_f2_$sp[0] + 0)->_int;
    break;
    case _1_f2__Mult_unsigned_long_unsigned_long2unsigned_long$right_STA_0$result_STA_0$left_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_unsigned_long = (_1_f2_$sp[0] + -1)->_unsigned_long * (_1_f2_$sp[0] + 0)->_unsigned_long;
    (_1_f2_$sp[0]) --;
    break;
    case _1_f2__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + 1)->_unsigned_long = *((unsigned long *)_1_f2_$pc[0]);
    (_1_f2_$sp[0]) ++;
    _1_f2_$pc[0] += 8;
    break;
    case _1_f2__PlusA_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_1_f2_$pc[0]) ++;
    (_1_f2_$sp[0] + -1)->_int = (_1_f2_$sp[0] + 0)->_int + (_1_f2_$sp[0] + -1)->_int;
    (_1_f2_$sp[0]) --;
    break;
    }
  }
}
}
void global_arg0_i$nit(void) 
{ 


  {
  global_arg0 = 0L;
}
}
int old_f1(int a ) 
{ 


  {
  if (a == 0) {
    return (1);
  } else {
    return (10);
  }
}
}
void global_arg1_i$nit(void) 
{ 


  {
  global_arg1 = 0L;
}
}
void global_arg4_i$nit(void) 
{ 


  {
  global_arg4 = 0L;
}
}
void global_arg5_i$nit(void) 
{ 


  {
  global_arg5 = 0L;
}
}
int old_f2(int a )  __attribute__((__annotate__("fla"), __annotate__("bcf"), __annotate__("sub"))) ;
int old_f2(int a ) 
{ 


  {
  if (a == 0) {
    return (1);
  } else {
    return (10);
  }
}
}
void fuzz_start(void) 
{ 


  {
  return;
}
}
void global_arg3_i$nit(void) 
{ 


  {
  global_arg3 = 0L;
}
}
int compare(long *r1p , long *r2p , long a0 , long a1 , long a2 , long a3 , long a4 ,
            long a5 ) 
{ 
  long r1 ;
  long tmp ;
  long r2 ;
  long tmp___0 ;

  {
  printf((char const   */* __restrict  */)"Starting f1\n");
  fflush(stdout);
  tmp = f1((unsigned char *)a0, (int )a1);
  r1 = tmp;
  printf((char const   */* __restrict  */)"Completed f1\n");
  fflush(stdout);
  printf((char const   */* __restrict  */)"Starting adapted_f1\n");
  fflush(stdout);
  tmp___0 = wrap_f2(a0, a1);
  r2 = tmp___0;
  printf((char const   */* __restrict  */)"Completed adapted_f1\n");
  fflush(stdout);
  if (r1 == r2) {
    printf((char const   */* __restrict  */)"Match\n");
  } else {
    printf((char const   */* __restrict  */)"Mismatch\n");
  }
  if (r1p) {
    *r1p = r1;
  }
  if (r2p) {
    *r2p = r2;
  }
  return (r1 == r2);
}
}
void megaInit(void) 
{ 


  {
  global_arg0_i$nit();
  global_arg1_i$nit();
  global_arg2_i$nit();
  global_arg3_i$nit();
  global_arg4_i$nit();
  global_arg5_i$nit();
}
}
int main(int argc , char **argv ) 
{ 
  FILE *fh ;
  FILE *fh_ce ;
  int *tmp ;
  char *tmp___0 ;
  long args[6] ;
  long r1 ;
  long r2 ;
  int i ;
  char *s ;
  unsigned short const   **tmp___1 ;
  long a ;
  long b ;
  long c ;
  long d ;
  long e ;
  long f ;
  long a___0 ;
  long b___0 ;
  long c___0 ;
  long d___0 ;
  long e___0 ;
  long f___0 ;
  int *tmp___2 ;
  char *tmp___3 ;
  int is_eq ;
  int tmp___4 ;
  int tmp___5 ;

  {
  megaInit();
  if (argc == 5) {
    if ((int )*(*(argv + 3) + 0) == 102) {
      fh = fopen((char const   */* __restrict  */)*(argv + 4), (char const   */* __restrict  */)"r");
    }
  }
  if (argc == 5) {
    if ((int )*(*(argv + 3) + 0) == 103) {
      fh_ce = fopen((char const   */* __restrict  */)*(argv + 4), (char const   */* __restrict  */)"r");
      if (! fh_ce) {
        tmp = __errno_location();
        tmp___0 = strerror(*tmp);
        fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Failed to open %s for reading: %s\n",
                *(argv + 4), tmp___0);
        return (1);
      }
    }
  }
  fuzz_start();
  if (argc < 4) {
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Usage: two-funcs <f1num> <f2num> a [0-6 args]\n");
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"    or two-funcs <f1num> <f2num> g\n");
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"    or two-funcs <f1num> <f2num> f <fname or ->\n");
    exit(1);
  }
  if ((int )*(*(argv + 3) + 0) == 97) {
    args[0] = 0L;
    args[1] = 0L;
    args[2] = 0L;
    args[3] = 0L;
    args[4] = 0L;
    args[5] = 0L;
    i = 0;
    while (1) {
      if (i < 6) {
        if (! (i + 4 < argc)) {
          break;
        }
      } else {
        break;
      }
      s = *(argv + (i + 4));
      tmp___1 = __ctype_b_loc();
      if ((int const   )*(*tmp___1 + (int )*(s + 0)) & 2048) {
        args[i] = atol((char const   *)s);
      } else {
        args[i] = (long )s;
      }
      i ++;
    }
    compare(& r1, & r2, args[0], args[1], args[2], args[3], args[4], args[5]);
    if (r1 == r2) {
      printf((char const   */* __restrict  */)"Both %ld\n", r1);
    } else {
      printf((char const   */* __restrict  */)"Difference %ld vs. %ld\n", r1, r2);
    }
  } else
  if ((int )*(*(argv + 3) + 0) == 103) {
    fscanf((FILE */* __restrict  */)fh_ce, (char const   */* __restrict  */)"%lx %lx %lx %lx %lx %lx",
           & a, & b, & c, & d, & e, & f);
    printf((char const   */* __restrict  */)"read ce inputs\n");
    fflush(stdout);
    compare((long *)0, (long *)0, a, b, c, d, e, f);
  } else
  if ((int )*(*(argv + 3) + 0) == 102) {
    if ((int )*(*(argv + 4) + 0) == 45) {
      if ((int )*(*(argv + 4) + 1) == 0) {
        fh = stdin;
      } else {
        goto _L;
      }
    } else
    _L: /* CIL Label */ 
    if (! fh) {
      tmp___2 = __errno_location();
      tmp___3 = strerror(*tmp___2);
      fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Failed to open %s for reading: %s\n",
              *(argv + 4), tmp___3);
      return (1);
    }
    while (1) {
      tmp___5 = fscanf((FILE */* __restrict  */)fh, (char const   */* __restrict  */)"%lx %lx %lx %lx %lx %lx",
                       & a___0, & b___0, & c___0, & d___0, & e___0, & f___0);
      if (! (tmp___5 != -1)) {
        break;
      }
      printf((char const   */* __restrict  */)"read a test\n");
      fflush(stdout);
      tmp___4 = compare((long *)0, (long *)0, a___0, b___0, c___0, d___0, e___0, f___0);
      is_eq = tmp___4;
      if (! is_eq) {
        exit(1);
      }
    }
    printf((char const   */* __restrict  */)"All tests succeeded!\n");
  } else {
    fprintf((FILE */* __restrict  */)stderr, (char const   */* __restrict  */)"Unhandled command argument\n");
    exit(1);
  }
  return (0);
}
}
long wrap_f2(long a0 , long a1 ) 
{ 
  long tmp ;

  {
  tmp = f2(5, 3, (int )a0, (unsigned char *)a1);
  return (tmp);
}
}
