#!/bin/bash -l        
#PBS -l walltime=04:00:00,nodes=1:ppn=8,pmem=2gb 
#PBS -m abe 
#PBS -M vaibhav@umn.edu
#PBS -o $HOME/clamp/output-81-$PBS_JOBID.log
#PBS -e $HOME/clamp/error-81-$PBS_JOBID.log

export FNUM=2
cd $HOME/clamp/arm-1;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 1 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-2;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 2 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-3;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 3 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-4;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 4 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-5;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 5 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-6;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 6 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-7;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 7 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-8;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 8 3 20 $FNUM 2 - return >> logs/9.log &
wait
