#!/bin/bash -l        
#PBS -l walltime=04:00:00,nodes=1:ppn=8,pmem=2gb 
#PBS -m abe 
#PBS -M vaibhav@umn.edu 
#PBS -o $HOME/clamp/output-82-$PBS_JOBID.log
#PBS -e $HOME/clamp/error-82-$PBS_JOBID.log

export FNUM=2
cd $HOME/clamp/arm-9;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 9 3 20 $FNUM 2 - return >> logs/9.log &
cd $HOME/clamp/arm-10;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 10 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-11;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 11 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-12;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 12 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-13;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 13 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-14;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 14 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-15;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 15 3 20 $FNUM 2 - return >>logs/9.log &
cd $HOME/clamp/arm-16;
FUZZBALL_LOC=$HOME/fuzzball-adaptorsynth/exec_utils/fuzzball perl run-fragments-msi.pl /home/smccaman/vaibhav/fragments8 16 16 3 20 $FNUM 2 - return >>logs/9.log &
wait
