#!/bin/bash -l        
#PBS -l walltime=04:00:00,nodes=1:ppn=8,pmem=2gb 
#PBS -m abe 
#PBS -M vaibhav@umn.edu 
cd ~/clamp
cd $HOME/clamp/arm-1;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 1 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-2;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 2 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-3;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 3 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-4;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 4 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-5;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 5 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-6;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 6 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-7;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 7 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
cd $HOME/clamp/arm-8;
perl run-fragments-msi.pl /home/smccaman/vaibhav/fuzzball-synth/eg/arm/fragments7 16 8 3 20 0 2 constant-bounds.lst >> logs/6-ty.log &
wait
