#!/bin/bash -l        
#PBS -l walltime=01:00:00,nodes=1:ppn=1,pmem=1gb 
#PBS -m abe 
#PBS -M vaibhav@umn.edu 
#PBS -o $HOME/fuzzball-synth/eg/arm/logs/report-metrics-output.log
#PBS -e $HOME/fuzzball-synth/eg/arm/logs/report-metrics-error.log

# cd $HOME/fuzzball-synth/eg/arm/msi-scripts/;
# perl trim-log.pl 6-ty-4.log 2 16 /home/smccaman/vaibhav/clamp-allconsts-typeconv-smallret >& logs/trim-clamp-allconsts-typeconv-smallret.log

cd $HOME/fuzzball-synth/eg/arm/;
perl report-metrics.pl 9.log 16 base_dirs.lst
wait
