#!/bin/bash -l        
#PBS -l walltime=01:00:00,nodes=1:ppn=1,pmem=1gb 
#PBS -m abe 
#PBS -M vaibhav@umn.edu 
#PBS -o /home/smccaman/vaibhav/fuzzball-synth/eg/arm/msi-scripts/logs/report-metrics-arithmetic.log
#PBS -e /home/smccaman/vaibhav/fuzzball-synth/eg/arm/msi-scripts/logs/report-metrics-error.log

# cd $HOME/fuzzball-synth/eg/arm/msi-scripts/;
# perl trim-log.pl 6-ty-4.log 2 16 /home/smccaman/vaibhav/clamp-allconsts-typeconv-smallret >& logs/trim-clamp-allconsts-typeconv-smallret.log

cd /home/smccaman/vaibhav/fuzzball-synth/eg/arm/msi-scripts;
perl report-metrics.pl 13.log 32 base-dirs.lst &
wait
